project:
  type: book
  output-dir: docs

book:
  title: "Modelos de Regresión"
  author: "Víctor Aceña - Carmen Lancho - Isaac Martín"
  date: "2025-01-23"
  search: true
  chapters:
    - index.qmd
    - tema1.qmd
    - tema2.qmd
    - tema3.qmd
    - conclusiones.qmd
    - references.qmd
  cover-image: DSLab_logo_2.png

bibliography: references.bib

format:
  html:
    theme: cerulean
    lang: es
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual







